export const BASE_URL = 'http://192.168.1.12:5000';
export const TEAM_OFFICE_BASE_URL = '/api/etimeoffice';
export const TEAM_OFFICE_AUTH_TOKEN = 'c3VwcG9ydDpzdXBwb3J0OnN1cHBvcnRAMTp0cnVl';

export const API_ENDPOINTS = {
  LOGIN: `${BASE_URL}/api/login`,
  REGISTER: `${BASE_URL}/api/register`,
  PROFILE: `${BASE_URL}/api/profile`,
  PROFILE_UPDATE: `${BASE_URL}/api/profile/update`,
  PROFILE_ABOUT: `${BASE_URL}/api/profile/about`,
  PROFILE_MANAGER: `${BASE_URL}/api/profile/manager`,
  PROFILE_UPLOAD_DOC: `${BASE_URL}/api/profile/upload-doc`,
  EMPLOYEE_PROFILE_GET: (id) => `${BASE_URL}/api/employee-profile/${id}`,
  EMPLOYEE_PROFILE_ALL: `${BASE_URL}/api/admin/employee-profiles`,
  EMPLOYEE_PROFILE_UPDATE: `${BASE_URL}/api/employee-profile/update`,
  EMPLOYEE_PROFILE_PUT: (id) => `${BASE_URL}/api/employee-profile/${id}`,
  EMPLOYEE_PROFILE_DELETE: (id) => `${BASE_URL}/api/employee-profile/${id}`,
  THREADS: `${BASE_URL}/api/threads`,
  THREAD_REACT: (id) => `${BASE_URL}/api/threads/${id}/react`,
  THREAD_REACTORS: (id, type) => `${BASE_URL}/api/threads/${id}/reactors${type ? `?type=${encodeURIComponent(type)}` : ''}`,
  THREAD_BADGE: (id) => `${BASE_URL}/api/threads/${id}/badge`,
  THREAD_COMMENT: (id) => `${BASE_URL}/api/threads/${id}/comment`,
  THREAD_COMMENTS: (id) => `${BASE_URL}/api/threads/${id}/comments`,
  THREAD_UPDATE: (id) => `${BASE_URL}/api/threads/${id}`,
  THREAD_DELETE: (id) => `${BASE_URL}/api/threads/${id}`,
  THREAD_USER: (userId) => `${BASE_URL}/api/threads/user/${userId}`,
  COMMENT_DELETE: (threadId, commentId) => `${BASE_URL}/api/threads/${threadId}/comments/${commentId}`,
  COMMENT_UPDATE: (threadId, commentId) => `${BASE_URL}/api/threads/${threadId}/comments/${commentId}`,
  TASKS: `${BASE_URL}/api/tasks`,
  TASK_UPDATES: `${BASE_URL}/api/task-updates`,
  TEAMS: `${BASE_URL}/api/teams`,
  EMPLOYEES: `${BASE_URL}/api/employees`,
  HOLIDAYS: `${BASE_URL}/api/holidays`,
  COURSES: `${BASE_URL}/api/courses`,
  SUGGESTIONS: `${BASE_URL}/api/suggestions`,
  ASSIGN_TASK: `${BASE_URL}/api/assign-task`,
  ASSIGNED_TASKS_GET: `${BASE_URL}/api/tasks/all-assigned`,
  ALERTS: `${BASE_URL}/api/notifications`,
  USERS: `${BASE_URL}/api/users`,
  ATTENDANCE: `${BASE_URL}/api/attendance`,
  NEW_JOINEES: `${BASE_URL}/api/new-joinees`,
  NEWJOINEE_COURSES: `${BASE_URL}/api/newjoinee-courses`,
  SUPPORT_TICKETS: `${BASE_URL}/api/support-tickets`,
  TASKS_ASSIGNED: (uid) => `${BASE_URL}/api/tasks/assigned/${uid}`,
  ATTENDANCE_LOGS_GET: `${BASE_URL}/api/attendance_logs`,
  ATTENDANCE_PUNCH_UPDATE: `${BASE_URL}/api/attendance/update-punch-time`,
  LEAVES_GET: `${BASE_URL}/api/leaves/all`,
  PAYSLIPS: `${BASE_URL}/api/payslips`,
  PAY_SLIP_POST: `${BASE_URL}/api/pay_slip`,
  SERVICE_CERTIFICATES_GET: `${BASE_URL}/api/admin/service-certificates`,
  SERVICE_CERTIFICATE_UPDATE: (id) => `${BASE_URL}/api/admin/service-certificates/${id}`,
  SERVICE_CERTIFICATE_REQUEST: `${BASE_URL}/api/service-certificates`,
  RESIGNATIONS_GET: `${BASE_URL}/api/admin/resignations`,
  RESIGNATION_UPDATE: (id) => `${BASE_URL}/api/admin/resignations/${id}/review`,
  RESIGNATION_REQUEST: `${BASE_URL}/api/resignations`,
  REWARDS: `${BASE_URL}/api/rewards`,
  REWARDS_HISTORY: `${BASE_URL}/api/admin/rewards/history`,
  REWARD_EDIT: (id) => `${BASE_URL}/api/rewards/${id}`,
  REWARD_DELETE: (id) => `${BASE_URL}/api/rewards/${id}`,
  REWARD_CATEGORIES: `${BASE_URL}/api/rewards/categories`,
  REWARDS_GIVE: `${BASE_URL}/api/rewards`,
  LEADERBOARD_ALL: `${BASE_URL}/api/employees/leaderboard/all`,
  NOTIFICATIONS_BY_USER: (uid) => `${BASE_URL}/api/notifications/${uid}`,
  ASSETS: `${BASE_URL}/api/assets`,
  ASSET_UPDATE: (id) => `${BASE_URL}/api/assets/${id}`,
  JOB_APPLICATIONS: `${BASE_URL}/api/job-applications`,
  JOB_APPLICATION_UPDATE: (id) => `${BASE_URL}/api/job-applications/${id}`,
  JOB_POSTINGS: `${BASE_URL}/api/job-postings`,
  JOB_POSTING_PUT: (id) => `${BASE_URL}/api/job-postings/${id}`,
  JOB_POSTING_DELETE: (id) => `${BASE_URL}/api/job-postings/${id}`,
};
